---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m0s
  secretRef:
    name: habor-creds
  type: oci
  url: oci://localhost:5000/charts
