---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: web-api-production
  namespace: flux-system
spec:
  spec:
  imageRepositoryRef:
    name: web-api
  filterTags:
    pattern: '^v?(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: '>=1.4.0 <2.0.0'
