apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - harbor-repository.yaml
  - image-repository.yaml
  - notification-alert.yaml
  - notification-provider.yaml
  - slack-webhook.enc.yaml
  - harbor-creds.enc.yaml
