apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo-api
spec:
  values:
    image:
      repository: host.minikube.internal:5000/charts/web-api # charts but this is the image
      tag: "1.4.6" # {"$imagepolicy": "flux-system:web-api-staging:tag"}
    replicaCount: 2
    config:
      PODINFO_UI_MESSAGE: "STAGING - deploy bang FluxCD"
      PODINFO_UI_COLOR: "#ffd700"
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: demo-api.staging.local
          paths:
            - path: /
              pathType: Prefix
    # imagePullSecrets:
    #   - name: habor-creds
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 256Mi
